name: image_pick_crop
description: ''
repository: 'https://github.com/wuzhengu/flutter_image_pick_crop'

publish_to: 'none'

version: 1.0.2

environment:
  sdk: '>=2.19.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  image_picker: ^1.0.0
  image_cropper: ^5.0.0

  flutter_native_image: ^0.0.6

  agu_dart:
    git:
      url: git@github.com:wuzhengu/agu_dart
      ref: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
